server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://47.96.143.152:3306/test01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Yjw970827
    driver-class-name: com.mysql.jdbc.Driver
#  mvc: 
#    static-path-pattern: /static/**
#    resources:
#      static-locations: classpath:/static/  # 静态资源  
mybatis: 
  type-aliases-package: com.sitech.mybatis.dao
  configuration:
    call-setters-on-nulls: true 




